version: '3.8'

services:
  # --- ALTYAPI SERVİSLERİ ---
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true 
    ports:
      - "5341:80"

  # --- MİKROSERVİSLER ---
  authapi:
    build:
      context: .
      dockerfile: src/Services/AuthService/AuthApi/Dockerfile
    container_name: authapi
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=KayraExport;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - Jwt__SecurityKey=1d95192466435a1d771a3c56a4c0770f
    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started

  productionservice:
    build:
      context: .
      dockerfile: src/Services/ProductionService/Presentation/ProductionService.WebApi/Dockerfile
    container_name: productionservice
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=KayraExport;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
      - Jwt__SecurityKey=1d95192466435a1d771a3c56a4c0770f
    depends_on:
      sqlserver:
        condition: service_started
      redis:
        condition: service_started

  
  logservice:
    build:
      context: .
      dockerfile: src/Services/LogService/LogWebApi/Dockerfile
    container_name: logservice
    environment:
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - seq
      - redis

  apigateway:
    build:
      context: .
      dockerfile: src/Services/ApiGateway/ApiGateway/Dockerfile
    container_name: apigateway
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ReverseProxy__Clusters__auth-cluster__Destinations__authService__Address=http://authapi:8080
      - ReverseProxy__Clusters__production-cluster__Destinations__productionService__Address=http://productionservice:8080
      - Jwt__SecurityKey=1d95192466435a1d771a3c56a4c0770f
    depends_on:
      - authapi
      - productionservice